FROM maven:3.8.5-openjdk-17 AS build
WORKDIR /app
COPY pom.xml .
COPY src/ ./src
RUN mvn clean package -DskipTests

FROM openjdk:17-jdk-slim
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar
COPY src/main/resources/h2.properties /opt/h2/conf/h2.properties
ENTRYPOINT ["java", "-jar", "app.jar"]

FROM openjdk:17-jdk-alpine
COPY target/cep-api.jar app.jar
EXPOSE 8080 8082
ENTRYPOINT ["java","-jar","/app.jar"]

